/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import facade.Facade;

/**
 *
 * @author Esben
 */
public class tester {

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        Facade fc = new Facade();
        //Create the Dynamic Queries (or if possible, a named Query generated by the wizard) to solve the following problems:
        //All are in Facade, but here are tests to see if they work as they should.
        
        
        //Find all Students in the system
        System.out.println(fc.getAllStudents());
        
        //Find all Students in the System with the first name Anders
        fc.getAllStudentsByFirstName("Anders");
        
        //Insert a new Student into the system
        //Remember to comment out after he has come into existance
//        Student stud = new Student("Peter", "HvadEndDetMestNormaleEfternavnEr");
//        fc.createStudent(stud);
        
        //Assign a new student to a semester
        fc.assignStudent(fc.getAllStudentsByFirstName("Peter").get(0), 3);
        
        //Find all Students in the system with the last name And
        System.out.println(fc.getAllStudentsByLastName("And"));
        
        //Find the total number of students, for a semester given the semester name as parameter.
        System.out.println(fc.StudentCountInSem("CLdat-b14e"));
        
        //Find the total number of students in all semesters.
        System.out.println(fc.StudentCount());
        
        //Find the teacher who teaches the most semesters.
        //Didn't have time.
    }

}
